server:
  port: 7777
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: *
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
